image:
- Ubuntu1804
- Visual Studio 2017

matrix:
  fast_finish: true

build_script:
- pwsh: >-
    '# BUILD'
    
    dir env:
    
    [Environment]::MachineName
    
    $PSVersionTable | Format-Table -Auto
    
    Get-Variable | Format-Table -Auto
    
    Get-ChildItem | Format-Table -Auto
    
    throw 'Ack! Stop the build!'
    
    exit 1
